#!/usr/bin/env python3

from pathlib import Path

from renderer_html import RendererHtml
from test_renderer_html import command_list
from help_parser import HelpParser

cmd = "getblockstats"

inputfile = Path(__file__).parent / "test_data" / cmd
outputfile = Path(__file__).parent / "test_data" / "html" / (cmd + ".html")

renderer = RendererHtml()
renderer.command_list = command_list()

cmd = "getblockstats"
with inputfile.open() as f:
    help_output = f.read()
    help_data = HelpParser().parse_help_command(help_output)
with outputfile.open("w") as f:
    f.write(renderer.render_command(cmd, help_data))
